### ISSUE TITLE
user tab error message

### ISSUE THREAD

**Issue by Chinese1904** [open-classifieds/openclassifieds2#1619]
when trying to browse to the user tab, there is an error message

2015-12-01 16:06:49 --- ERROR: Kohana_Exception [ 0 ]: The ads_count property does not exist in the Model_User class ~ APPPATH/kohana/modules/orm/classes/Kohana/ORM.php [ 687 ] in /var/www/classilist/oc/kohana/system/classes/Kohana/Kohana/Exception.php:110

**Comment by neo22s** [comment]
Which url?

**Comment by Chinese1904** [comment]
If you go to public profile and then press the user tab

**Comment by neo22s** [comment]
I still can not find it :S without an url its really difficult. 

Public profile you mean any users profile, but users tab? I get lost there.

**Comment by Chinese1904** [comment]
If you go to your public profile and click Users in the navigation
![Image of Error](http://i.imgur.com/N5P7cdp.png)
then this error appears
![Image of Error2](http://i.imgur.com/8BexAPM.png)

I noticed that usually the first time I try it, it works, then if I go back and click the user tab again, the error comes up.

**Comment by neo22s** [comment]
ok, the URL is http://classilist.org/user

But seems absolutely random :S

I will review.

**Comment by neo22s** [comment]
I can not reproduce it anywhere else :S

@oliverds can you? also the ads_count should always exists since its in the query.

**Comment by oliverds** [comment]
On reoc.lo it seems fine but if I test it on my reoc-26.lo, first time it works but then after refresh the page I get:

<img width="877" alt="screen shot 2015-12-02 at 09 49 50" src="https://cloud.githubusercontent.com/assets/7003648/11535594/24d7dfc4-98da-11e5-932a-07e9f1dfa211.png">

!Weird!

**Comment by neo22s** [comment]
hey @Chinese1904 check this commit https://github.com/open-classifieds/openclassifieds2/commit/090e511ab08a86ff8a83b473d5c6bf74d143b252 it fixes it ;)

**Comment by imariuss** [comment]
Hi,
When i click on users link from breadcrumb
![2016-05-20_15-49-03](https://cloud.githubusercontent.com/assets/15650100/15429744/9500fecc-1ea2-11e6-9ac2-0537d97488a4.jpg)

 i get  this  error :

![2016-05-20_15-51-42](https://cloud.githubusercontent.com/assets/15650100/15429785/c627d958-1ea2-11e6-8e85-f0640871111a.jpg)

This is the error log: 
<?php defined('SYSPATH') OR die('No direct script access.'); ?>

2016-05-20 15:24:30 --- ERROR: Kohana_Exception [ 0 ]: The ads_count property does not exist in the Model_User class ~ APPPATH/kohana/modules/orm/classes/Kohana/ORM.php [ 760 ] in /home/incontri/public_html/bakeca18piu.it/oc/kohana/system/classes/Kohana/Kohana/Exception.php:110  


Is there a way to fix that?  

Thank you

**Comment by oliverds** [comment]
@imariuss 

Do you have the latest version? This bug was fixed on 2.6.1.

Please use [our forums](https://forums.open-classifieds.com/) if you require support.

**Comment by imariuss** [comment]
yes . i use the last version 2.7.1

**Comment by congaframe** [comment]
I can confirm, this issue still exists on 2.7.0 as well.
However, I'm receiving 2 different errors on 2 different sites ( setting up on the same server environment)
1st one: 
```
Since you are logged in as admin only you can see this message:

The ads_count property does not exist in the Model_User class
It's been logged in Panel->Tools->Logs for more information regarding this error.
```
the 2nd site doesn't show above message, just: 
```
Sorry!
Something went wrong with your request. This incident is logged and we are already notified about this problem.

You can go Back or to our Home page.
```

But the error logged in Admin Panel is the same:
```
2016-05-24 23:20:44 --- ERROR: Kohana_Exception [ 0 ]: The ads_count property does not exist in the Model_User class ~ APPPATH/kohana/modules/orm/classes/Kohana/ORM.php [ 760 ] in /var/www/staging/oc/kohana/system/classes/Kohana/Kohana/Exception.php:110
```

**Comment by imariuss** [comment]
In my case , this issue  was solved  by the php version.
Make sure  you  have php 5.5+ version set  as default in your cPanel
Hope it help

**Comment by neo22s** [comment]
please use php 5.5 and update to latest 2.7.1
